plugins {
    id 'com.android.library'
    id 'jacoco'
}
apply plugin: 'kotlin-android'

android {
    compileSdk 37
    buildToolsVersion '36.0.0'

    defaultConfig {
        minSdk 29
        //Waiting for api 32 sources
        //noinspection OldTargetApi

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
        targetSdk 37
    }

    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    namespace 'com.particlesdevs.photoncamera.circularbarlib'
    buildFeatures {
        viewBinding false
    }
    lint {
        targetSdk 36
    }
    testOptions {
        targetSdk 36
    }
    compileSdkMinor 0
}

dependencies {
    implementation 'androidx.core:core-ktx:1.19.0'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:2.4.10'
    implementation 'androidx.test:monitor:1.8.0'
    testImplementation 'org.testng:testng:7.12.0'
    implementation 'androidx.test.ext:junit:1.3.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'junit:junit:4.13.2'

/*    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'*/
}
repositories {
    mavenCentral()
    maven {
        url "https://jitpack.io"
    }
}