plugins {
    id 'com.android.library'
    id 'jacoco'
}
apply plugin: 'kotlin-android'

android {
    compileSdk 35
    buildToolsVersion '35.0.0'

    defaultConfig {
        minSdk 30
        targetSdk 35
//Waiting for api 32 sources
        //noinspection OldTargetApi

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    namespace 'com.particlesdevs.photoncamera.circularbarlib'
    buildFeatures {
        viewBinding false
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.16.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.test:monitor:1.7.2'
    testImplementation 'org.testng:testng:7.11.0'
    implementation 'androidx.test.ext:junit:1.2.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'junit:junit:4.13.2'

/*    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'*/
}
repositories {
    mavenCentral()
}